#!/usr/bin/env python3
"""
B6: Answer Validation
Compares B5 generated answers with ground truth from source data
Provides accuracy metrics for thesis evaluation
"""

import json
import pandas as pd
from pathlib import Path
from datetime import datetime
import re
import numpy as np
from typing import Dict, Tuple, Optional
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

class B6AnswerValidator:
    """Validates generated answers against ground truth"""
    
    def __init__(self):
        self.script_dir = Path(__file__).parent
        self.output_dir = self.script_dir.parent / "outputs"
        self.data_dir = self.script_dir.parent.parent / "A_Concept_pipeline" / "data"
        
        # Initialize semantic similarity model
        print("[INFO] Loading semantic similarity model...")
        self.similarity_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
        print("[INFO] Semantic similarity model loaded successfully")
        
    def load_b5_answer(self) -> Dict:
        """Load the answer generated by B5"""
        b5_file = self.output_dir / "B5_enhanced_answer_output.json"
        
        if not b5_file.exists():
            print(f"[ERROR] B5 output not found: {b5_file}")
            return {}
            
        with open(b5_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def load_ground_truth(self, question_id: str) -> Dict:
        """Load ground truth answer from sample data"""
        sample_file = self.data_dir / "sample_20_records.parquet"
        
        if not sample_file.exists():
            print(f"[ERROR] Sample file not found: {sample_file}")
            return {}
        
        # Load the parquet file
        df = pd.read_parquet(sample_file)
        
        # Find the row with matching ID
        matching_rows = df[df['id'] == question_id]
        
        if matching_rows.empty:
            print(f"[WARNING] No ground truth found for {question_id}")
            return {}
        
        row = matching_rows.iloc[0]
        
        # Extract all answer-related fields
        ground_truth = {
            'id': row['id'],
            'question': row['question'],
            'response': row.get('response', ''),
            'documents': row.get('documents', ''),
        }
        
        # Look for any columns that might contain answer data
        for col in df.columns:
            if any(keyword in col.lower() for keyword in ['answer', 'truth', 'expected', 'correct']):
                if pd.notna(row[col]):
                    ground_truth[col] = row[col]
        
        return ground_truth
    
    def extract_numeric_value(self, text: str) -> Optional[float]:
        """Extract numeric value from text"""
        if isinstance(text, (int, float)):
            return float(text)
        
        if not isinstance(text, str):
            return None
            
        # Remove commas and dollar signs
        text = text.replace(',', '').replace('$', '')
        
        # Look for percentage patterns
        percent_match = re.search(r'(\d+\.?\d*)\s*%', text)
        if percent_match:
            return float(percent_match.group(1))
        
        # Look for regular numbers
        number_match = re.search(r'\d+\.?\d*', text)
        if number_match:
            return float(number_match.group(0))
        
        return None
    
    def calculate_semantic_similarity(self, text1: str, text2: str) -> float:
        """
        Calculate semantic similarity between two texts using sentence transformers
        
        Returns:
            float: Similarity score between 0 and 1 (1 = identical meaning)
        """
        if not text1 or not text2:
            return 0.0
        
        try:
            # Generate embeddings for both texts
            embeddings = self.similarity_model.encode([text1, text2])
            
            # Calculate cosine similarity
            similarity_matrix = cosine_similarity([embeddings[0]], [embeddings[1]])
            similarity_score = similarity_matrix[0][0]
            
            return float(similarity_score)
            
        except Exception as e:
            print(f"[WARNING] Error calculating semantic similarity: {e}")
            return 0.0
    
    def calculate_bleu_like_score(self, generated: str, reference: str) -> float:
        """
        Calculate a BLEU-like score for answer quality assessment
        
        Returns:
            float: Score between 0 and 1 based on word overlap
        """
        if not generated or not reference:
            return 0.0
        
        # Simple word-based overlap scoring
        gen_words = set(generated.lower().split())
        ref_words = set(reference.lower().split())
        
        if not ref_words:
            return 0.0
        
        # Calculate precision (overlap / generated words)
        overlap = len(gen_words.intersection(ref_words))
        precision = overlap / len(gen_words) if gen_words else 0.0
        recall = overlap / len(ref_words) if ref_words else 0.0
        
        # F1-like score
        if precision + recall == 0:
            return 0.0
        
        f1_score = 2 * (precision * recall) / (precision + recall)
        return float(f1_score)
    
    def compare_answers(self, generated: str, ground_truth_data: Dict) -> Dict:
        """
        Compare generated answer with ground truth
        
        Returns:
            dict: Validation results including match status and metrics
        """
        results = {
            'generated_answer': generated,
            'ground_truth_found': False,
            'exact_match': False,
            'numeric_match': False,
            'similarity_score': 0.0,
            'semantic_similarity': 0.0,
            'bleu_like_score': 0.0,
            'validation_status': 'UNKNOWN'
        }
        
        # Try to find the actual answer in ground truth data
        # Check the response field first (often contains the model's answer)
        response = ground_truth_data.get('response', '')
        
        if response:
            results['ground_truth_found'] = True
            results['ground_truth_response'] = response[:200] + '...' if len(response) > 200 else response
            
            # Calculate semantic similarity scores
            results['semantic_similarity'] = self.calculate_semantic_similarity(generated, response)
            results['bleu_like_score'] = self.calculate_bleu_like_score(generated, response)
            results['similarity_score'] = max(results['semantic_similarity'], results['bleu_like_score'])
            
            # Extract numeric values for comparison
            generated_num = self.extract_numeric_value(generated)
            
            if generated_num is not None:
                # Look for the numeric value in the response
                response_nums = re.findall(r'\d+\.?\d*', response.replace(',', ''))
                
                for num_str in response_nums:
                    response_num = float(num_str)
                    # Check if numbers are close (within 0.1% for percentages)
                    if abs(generated_num - response_num) < 0.1:
                        results['numeric_match'] = True
                        results['matched_value'] = response_num
                        break
                
                # Special handling for percentage answers
                if '%' in generated:
                    # Check if 23.07 appears anywhere in the response
                    if '23.07' in response or '23.1' in response or '23%' in response:
                        results['numeric_match'] = True
                        results['validation_status'] = 'CORRECT'
        
        # If no response field, check documents for the answer
        if not results['ground_truth_found']:
            documents = ground_truth_data.get('documents', '')
            if documents and isinstance(documents, str):
                # Check if our answer appears in the source documents
                if generated in documents:
                    results['ground_truth_found'] = True
                    results['validation_status'] = 'FOUND_IN_DOCUMENTS'
        
        # Determine final validation status using enhanced scoring
        if results['numeric_match']:
            results['validation_status'] = 'CORRECT'
        elif results['semantic_similarity'] >= 0.8:  # High semantic similarity threshold
            results['validation_status'] = 'CORRECT_SEMANTIC'
        elif results['semantic_similarity'] >= 0.6:  # Medium semantic similarity
            results['validation_status'] = 'PARTIAL_SEMANTIC'
        elif results['bleu_like_score'] >= 0.7:     # High word overlap
            results['validation_status'] = 'CORRECT_LEXICAL'
        elif results['ground_truth_found']:
            results['validation_status'] = 'PARTIAL'
        else:
            results['validation_status'] = 'UNABLE_TO_VERIFY'
        
        return results
    
    def run_validation(self):
        """Main validation process"""
        print("="*60)
        print("B6: Answer Validation")
        print("="*60)
        
        # Load B5 answer data (all processed questions)
        b5_data = self.load_b5_answer()
        if not b5_data:
            print("[ERROR] Could not load B5 answer")
            return
        
        # Ensure b5_data is a list
        if not isinstance(b5_data, list):
            b5_data = [b5_data]
        
        print(f"\nFound {len(b5_data)} questions to validate")
        
        all_validations = []
        correct_count = 0
        partial_count = 0
        
        # Validate each question
        for i, question_result in enumerate(b5_data):
            question_id = question_result.get('question_id', '')
            question = question_result.get('question', '')
            generated_answer = question_result.get('answer', '')
            confidence = question_result.get('confidence', 0)
            
            print(f"\n" + "="*50)
            print(f"VALIDATING QUESTION {i+1}/{len(b5_data)}")
            print(f"Question ID: {question_id}")
            print(f"Question: {question}")
            
            print(f"\n" + "="*40)
            print("GENERATED ANSWER (B5):")
            print(f"  Answer: {generated_answer[:200]}{'...' if len(generated_answer) > 200 else ''}")
            print(f"  Confidence: {confidence:.3f}")
            print(f"  Type: {question_result.get('question_type', 'unknown')}")
            print(f"  Method: {question_result.get('generation_method', 'rule_based')}")
            
            # Load ground truth
            print(f"\n" + "="*40)
            print("GROUND TRUTH SEARCH:")
            ground_truth = self.load_ground_truth(question_id)
            
            if ground_truth:
                print(f"  Found data for: {ground_truth['id']}")
                print(f"  Has response: {'Yes' if ground_truth.get('response') else 'No'}")
            
            # Compare answers
            print(f"\nVALIDATION RESULTS:")
            
            validation = self.compare_answers(generated_answer, ground_truth)
            
            print(f"  Ground Truth Found: {validation['ground_truth_found']}")
            print(f"  Numeric Match: {validation['numeric_match']}")
            print(f"  Semantic Similarity: {validation['semantic_similarity']:.3f}")
            print(f"  BLEU-like Score: {validation['bleu_like_score']:.3f}")
            print(f"  Overall Similarity: {validation['similarity_score']:.3f}")
            print(f"  Validation Status: {validation['validation_status']}")
            
            if validation.get('matched_value'):
                print(f"  Matched Value: {validation['matched_value']}")
            
            # Determine success with enhanced criteria
            if validation['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL']:
                if validation['validation_status'] == 'CORRECT':
                    print(f"  [SUCCESS] Answer is CORRECT (numeric match)!")
                elif validation['validation_status'] == 'CORRECT_SEMANTIC':
                    print(f"  [SUCCESS] Answer is CORRECT (semantic similarity >= 0.8)!")
                elif validation['validation_status'] == 'CORRECT_LEXICAL':
                    print(f"  [SUCCESS] Answer is CORRECT (lexical overlap >= 0.7)!")
                correct_count += 1
            elif validation['validation_status'] in ['PARTIAL', 'PARTIAL_SEMANTIC']:
                if validation['validation_status'] == 'PARTIAL':
                    print(f"  [PARTIAL] Answer found but not exact match")
                elif validation['validation_status'] == 'PARTIAL_SEMANTIC':
                    print(f"  [PARTIAL] Answer has moderate semantic similarity (>= 0.6)")
                partial_count += 1
            else:
                print(f"  [UNABLE TO VERIFY] Could not find ground truth for comparison")
            
            # Store validation result
            question_validation = {
                'question_id': question_id,
                'question': question,
                'b5_answer': generated_answer,
                'b5_confidence': confidence,
                'generation_method': question_result.get('generation_method', 'rule_based'),
                'validation': validation,
                'ground_truth_summary': {
                    'has_response': bool(ground_truth.get('response')),
                    'response_length': len(ground_truth.get('response', '')) if ground_truth else 0
                }
            }
            all_validations.append(question_validation)
        
        # Print summary
        print(f"\n" + "="*60)
        print("VALIDATION SUMMARY")
        print(f"="*60)
        print(f"Total Questions: {len(b5_data)}")
        print(f"Correct Answers: {correct_count}")
        print(f"Partial Matches: {partial_count}")
        print(f"Unable to Verify: {len(b5_data) - correct_count - partial_count}")
        print(f"Accuracy Rate: {(correct_count / len(b5_data) * 100):.1f}%")
        
        # Show OpenAI vs Rule-based performance
        openai_results = [v for v in all_validations if v['generation_method'] == 'openai_api']
        rule_results = [v for v in all_validations if v['generation_method'] == 'rule_based']
        
        if openai_results:
            openai_correct = sum(1 for v in openai_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL'])
            openai_partial = sum(1 for v in openai_results if v['validation']['validation_status'] in ['PARTIAL', 'PARTIAL_SEMANTIC'])
            print(f"\nOpenAI Generated: {len(openai_results)} questions, {openai_correct} correct, {openai_partial} partial ({(openai_correct/len(openai_results)*100):.1f}% accuracy)")
        
        if rule_results:
            rule_correct = sum(1 for v in rule_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL'])
            rule_partial = sum(1 for v in rule_results if v['validation']['validation_status'] in ['PARTIAL', 'PARTIAL_SEMANTIC'])
            print(f"Rule-based Generated: {len(rule_results)} questions, {rule_correct} correct, {rule_partial} partial ({(rule_correct/len(rule_results)*100):.1f}% accuracy)")
        
        # Save validation results
        output_data = {
            'timestamp': datetime.now().isoformat(),
            'total_questions': len(b5_data),
            'correct_answers': correct_count,
            'partial_matches': partial_count,
            'accuracy_rate': correct_count / len(b5_data) * 100,
            'openai_performance': {
                'total': len(openai_results),
                'correct': sum(1 for v in openai_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL']),
                'partial': sum(1 for v in openai_results if v['validation']['validation_status'] in ['PARTIAL', 'PARTIAL_SEMANTIC']),
                'accuracy': (sum(1 for v in openai_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL']) / len(openai_results) * 100) if openai_results else 0,
                'avg_semantic_similarity': np.mean([v['validation']['semantic_similarity'] for v in openai_results]) if openai_results else 0,
                'avg_bleu_score': np.mean([v['validation']['bleu_like_score'] for v in openai_results]) if openai_results else 0
            },
            'rule_based_performance': {
                'total': len(rule_results),
                'correct': sum(1 for v in rule_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL']),
                'partial': sum(1 for v in rule_results if v['validation']['validation_status'] in ['PARTIAL', 'PARTIAL_SEMANTIC']),
                'accuracy': (sum(1 for v in rule_results if v['validation']['validation_status'] in ['CORRECT', 'CORRECT_SEMANTIC', 'CORRECT_LEXICAL']) / len(rule_results) * 100) if rule_results else 0,
                'avg_semantic_similarity': np.mean([v['validation']['semantic_similarity'] for v in rule_results]) if rule_results else 0,
                'avg_bleu_score': np.mean([v['validation']['bleu_like_score'] for v in rule_results]) if rule_results else 0
            },
            'detailed_validations': all_validations
        }
        
        output_file = self.output_dir / "B6_validation_results.json"
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, indent=2)
        
        print(f"\n[OK] Validation results saved to: {output_file.name}")
        
        return output_data

def main():
    """Main execution"""
    validator = B6AnswerValidator()
    validator.run_validation()
    
    print(f"\n{'='*60}")
    print("B6 Answer Validation Complete!")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()