#!/usr/bin/env python3
"""
B6: Answer Validation
Compares B5 generated answers with ground truth from source data
Provides accuracy metrics for thesis evaluation
"""

import json
import pandas as pd
from pathlib import Path
from datetime import datetime
import re
from typing import Dict, Tuple, Optional

class B6AnswerValidator:
    """Validates generated answers against ground truth"""
    
    def __init__(self):
        self.script_dir = Path(__file__).parent
        self.output_dir = self.script_dir.parent / "outputs"
        self.data_dir = self.script_dir.parent.parent / "A_Concept_pipeline" / "data"
        
    def load_b5_answer(self) -> Dict:
        """Load the answer generated by B5"""
        b5_file = self.output_dir / "B5_enhanced_answer_output.json"
        
        if not b5_file.exists():
            print(f"[ERROR] B5 output not found: {b5_file}")
            return {}
            
        with open(b5_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def load_ground_truth(self, question_id: str) -> Dict:
        """Load ground truth answer from sample data"""
        sample_file = self.data_dir / "sample_20_records.parquet"
        
        if not sample_file.exists():
            print(f"[ERROR] Sample file not found: {sample_file}")
            return {}
        
        # Load the parquet file
        df = pd.read_parquet(sample_file)
        
        # Find the row with matching ID
        matching_rows = df[df['id'] == question_id]
        
        if matching_rows.empty:
            print(f"[WARNING] No ground truth found for {question_id}")
            return {}
        
        row = matching_rows.iloc[0]
        
        # Extract all answer-related fields
        ground_truth = {
            'id': row['id'],
            'question': row['question'],
            'response': row.get('response', ''),
            'documents': row.get('documents', ''),
        }
        
        # Look for any columns that might contain answer data
        for col in df.columns:
            if any(keyword in col.lower() for keyword in ['answer', 'truth', 'expected', 'correct']):
                if pd.notna(row[col]):
                    ground_truth[col] = row[col]
        
        return ground_truth
    
    def extract_numeric_value(self, text: str) -> Optional[float]:
        """Extract numeric value from text"""
        if isinstance(text, (int, float)):
            return float(text)
        
        if not isinstance(text, str):
            return None
            
        # Remove commas and dollar signs
        text = text.replace(',', '').replace('$', '')
        
        # Look for percentage patterns
        percent_match = re.search(r'(\d+\.?\d*)\s*%', text)
        if percent_match:
            return float(percent_match.group(1))
        
        # Look for regular numbers
        number_match = re.search(r'\d+\.?\d*', text)
        if number_match:
            return float(number_match.group(0))
        
        return None
    
    def compare_answers(self, generated: str, ground_truth_data: Dict) -> Dict:
        """
        Compare generated answer with ground truth
        
        Returns:
            dict: Validation results including match status and metrics
        """
        results = {
            'generated_answer': generated,
            'ground_truth_found': False,
            'exact_match': False,
            'numeric_match': False,
            'similarity_score': 0.0,
            'validation_status': 'UNKNOWN'
        }
        
        # Try to find the actual answer in ground truth data
        # Check the response field first (often contains the model's answer)
        response = ground_truth_data.get('response', '')
        
        if response:
            results['ground_truth_found'] = True
            results['ground_truth_response'] = response[:200] + '...' if len(response) > 200 else response
            
            # Extract numeric values for comparison
            generated_num = self.extract_numeric_value(generated)
            
            if generated_num is not None:
                # Look for the numeric value in the response
                response_nums = re.findall(r'\d+\.?\d*', response.replace(',', ''))
                
                for num_str in response_nums:
                    response_num = float(num_str)
                    # Check if numbers are close (within 0.1% for percentages)
                    if abs(generated_num - response_num) < 0.1:
                        results['numeric_match'] = True
                        results['matched_value'] = response_num
                        break
                
                # Special handling for percentage answers
                if '%' in generated:
                    # Check if 23.07 appears anywhere in the response
                    if '23.07' in response or '23.1' in response or '23%' in response:
                        results['numeric_match'] = True
                        results['validation_status'] = 'CORRECT'
        
        # If no response field, check documents for the answer
        if not results['ground_truth_found']:
            documents = ground_truth_data.get('documents', '')
            if documents and isinstance(documents, str):
                # Check if our answer appears in the source documents
                if generated in documents:
                    results['ground_truth_found'] = True
                    results['validation_status'] = 'FOUND_IN_DOCUMENTS'
        
        # Determine final validation status
        if results['numeric_match']:
            results['validation_status'] = 'CORRECT'
        elif results['ground_truth_found']:
            results['validation_status'] = 'PARTIAL'
        else:
            results['validation_status'] = 'UNABLE_TO_VERIFY'
        
        return results
    
    def run_validation(self):
        """Main validation process"""
        print("="*60)
        print("B6: Answer Validation")
        print("="*60)
        
        # Load B5 answer data (all processed questions)
        b5_data = self.load_b5_answer()
        if not b5_data:
            print("[ERROR] Could not load B5 answer")
            return
        
        # Ensure b5_data is a list
        if not isinstance(b5_data, list):
            b5_data = [b5_data]
        
        print(f"\nFound {len(b5_data)} questions to validate")
        
        all_validations = []
        correct_count = 0
        partial_count = 0
        
        # Validate each question
        for i, question_result in enumerate(b5_data):
            question_id = question_result.get('question_id', '')
            question = question_result.get('question', '')
            generated_answer = question_result.get('answer', '')
            confidence = question_result.get('confidence', 0)
            
            print(f"\n" + "="*50)
            print(f"VALIDATING QUESTION {i+1}/{len(b5_data)}")
            print(f"Question ID: {question_id}")
            print(f"Question: {question}")
            
            print(f"\n" + "="*40)
            print("GENERATED ANSWER (B5):")
            print(f"  Answer: {generated_answer[:200]}{'...' if len(generated_answer) > 200 else ''}")
            print(f"  Confidence: {confidence:.3f}")
            print(f"  Type: {question_result.get('question_type', 'unknown')}")
            print(f"  Method: {question_result.get('generation_method', 'rule_based')}")
            
            # Load ground truth
            print(f"\n" + "="*40)
            print("GROUND TRUTH SEARCH:")
            ground_truth = self.load_ground_truth(question_id)
            
            if ground_truth:
                print(f"  Found data for: {ground_truth['id']}")
                print(f"  Has response: {'Yes' if ground_truth.get('response') else 'No'}")
            
            # Compare answers
            print(f"\nVALIDATION RESULTS:")
            
            validation = self.compare_answers(generated_answer, ground_truth)
            
            print(f"  Ground Truth Found: {validation['ground_truth_found']}")
            print(f"  Numeric Match: {validation['numeric_match']}")
            print(f"  Validation Status: {validation['validation_status']}")
            
            if validation.get('matched_value'):
                print(f"  Matched Value: {validation['matched_value']}")
            
            # Determine success
            if validation['validation_status'] == 'CORRECT':
                print(f"  [SUCCESS] Answer is CORRECT!")
                correct_count += 1
            elif validation['validation_status'] == 'PARTIAL':
                print(f"  [PARTIAL] Answer found but not exact match")
                partial_count += 1
            else:
                print(f"  [UNABLE TO VERIFY] Could not find ground truth for comparison")
            
            # Store validation result
            question_validation = {
                'question_id': question_id,
                'question': question,
                'b5_answer': generated_answer,
                'b5_confidence': confidence,
                'generation_method': question_result.get('generation_method', 'rule_based'),
                'validation': validation,
                'ground_truth_summary': {
                    'has_response': bool(ground_truth.get('response')),
                    'response_length': len(ground_truth.get('response', '')) if ground_truth else 0
                }
            }
            all_validations.append(question_validation)
        
        # Print summary
        print(f"\n" + "="*60)
        print("VALIDATION SUMMARY")
        print(f"="*60)
        print(f"Total Questions: {len(b5_data)}")
        print(f"Correct Answers: {correct_count}")
        print(f"Partial Matches: {partial_count}")
        print(f"Unable to Verify: {len(b5_data) - correct_count - partial_count}")
        print(f"Accuracy Rate: {(correct_count / len(b5_data) * 100):.1f}%")
        
        # Show OpenAI vs Rule-based performance
        openai_results = [v for v in all_validations if v['generation_method'] == 'openai_api']
        rule_results = [v for v in all_validations if v['generation_method'] == 'rule_based']
        
        if openai_results:
            openai_correct = sum(1 for v in openai_results if v['validation']['validation_status'] == 'CORRECT')
            print(f"\nOpenAI Generated: {len(openai_results)} questions, {openai_correct} correct ({(openai_correct/len(openai_results)*100):.1f}%)")
        
        if rule_results:
            rule_correct = sum(1 for v in rule_results if v['validation']['validation_status'] == 'CORRECT')
            print(f"Rule-based Generated: {len(rule_results)} questions, {rule_correct} correct ({(rule_correct/len(rule_results)*100):.1f}%)")
        
        # Save validation results
        output_data = {
            'timestamp': datetime.now().isoformat(),
            'total_questions': len(b5_data),
            'correct_answers': correct_count,
            'partial_matches': partial_count,
            'accuracy_rate': correct_count / len(b5_data) * 100,
            'openai_performance': {
                'total': len(openai_results),
                'correct': sum(1 for v in openai_results if v['validation']['validation_status'] == 'CORRECT'),
                'accuracy': (sum(1 for v in openai_results if v['validation']['validation_status'] == 'CORRECT') / len(openai_results) * 100) if openai_results else 0
            },
            'rule_based_performance': {
                'total': len(rule_results),
                'correct': sum(1 for v in rule_results if v['validation']['validation_status'] == 'CORRECT'),
                'accuracy': (sum(1 for v in rule_results if v['validation']['validation_status'] == 'CORRECT') / len(rule_results) * 100) if rule_results else 0
            },
            'detailed_validations': all_validations
        }
        
        output_file = self.output_dir / "B6_validation_results.json"
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, indent=2)
        
        print(f"\n[OK] Validation results saved to: {output_file.name}")
        
        return output_data

def main():
    """Main execution"""
    validator = B6AnswerValidator()
    validator.run_validation()
    
    print(f"\n{'='*60}")
    print("B6 Answer Validation Complete!")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()